/* 素材库（Corpus）：全部可背诵素材，与孩子的掌握状态无关。
   字段契约（battle.js 的规则判定依赖它，改字段名要同步改判定）：
     slotTypes  该素材可以放进哪些槽位类型（见 quests.js 的 SLOT_TYPES）
     subjects   适用的描写对象；含「通用」表示不挑对象，任何题目都算契合
                铁律：文本里出现了「他/她」等性别代词的，不得再挂中性标签（同学/通用），
                否则写男生的题目会把写女生的句子当成完全契合放过去。
     stars      1-3 星，决定推荐年级与用对时的伤害
     grain      颗粒度：句 / 片段
     chunks     人工标注的词块，背诵验收按它切成词语级。join 后必须与 text 一字不差；
                app.js 里有自检，对不上就自动回退 Intl.Segmenter（再退到按标点切），
                所以标注写错不会让功能崩，只会退化成自动分词。
                自动分词实测会切出「人的脚/后跟」「他二话/没说」这类跨词块，
                读起来节奏是断的，会干扰记忆，所以词块必须人工标注，机器只兜底。
   注意：库里故意保留了少量「对象不符」的素材（例如只适合女生的外貌描写），
   它们是教学素材——放错对象时会触发半契合与改写建议，而不是被藏起来。 */

const CORPUS = [
  /* ===================== 写人 ===================== */
  { id:'p01', genre:'renwu', slotTypes:['opening'], subjects:['男生'], stars:2, grain:'句',
    text:'每个班里总有那么一个人，他一说话，周围就热闹起来，连老师都要停下来等他笑完。',
    chunks:['每个班里','总有那么一个人，','他一说话，','周围就热闹起来，','连老师都要','停下来','等他笑完。'] },
  { id:'p02', genre:'renwu', slotTypes:['opening'], subjects:['通用'], stars:1, grain:'句',
    text:'如果要我在班里挑一个最熟的人，我不用想第二个，答案马上就冒出来了。',
    chunks:['如果要我在班里','挑一个','最熟的人，','我不用想第二个，','答案','马上就冒出来了。'] },
  { id:'p03', genre:'renwu', slotTypes:['opening'], subjects:['同学'], stars:2, grain:'句',
    text:'说起我的同桌，我得先叹一口气，再笑一下，然后才舍得开始讲他的事。',
    chunks:['说起我的同桌，','我得先叹一口气，','再笑一下，','然后才舍得','开始讲他的事。'] },
  { id:'p04', genre:'renwu', slotTypes:['opening'], subjects:['老师'], stars:2, grain:'句',
    text:'在我心里，有一个人的名字，比「老师」这两个字更重，每次想起来都觉得沉。',
    chunks:['在我心里，','有一个人的名字，','比','「老师」','这两个字更重，','每次想起来','都觉得沉。'] },
  { id:'p05', genre:'renwu', slotTypes:['opening'], subjects:['妈妈'], stars:3, grain:'句',
    text:'世上有一种人，累得直不起腰，却还先问你饿不饿，再问自己累不累——那是我妈。',
    chunks:['世上有一种人，','累得直不起腰，','却还先问你饿不饿，','再问自己累不累','——','那是我妈。'] },

  { id:'p06', genre:'renwu', slotTypes:['appearance'], subjects:['男生'], stars:2, grain:'句',
    text:'他个子不高，排队总在第二个，晒得黑黑的，可跑起来全班谁也追不上。',
    chunks:['他个子不高，','排队总在第二个，','晒得黑黑的，','可跑起来','全班谁也追不上。'] },
  { id:'p07', genre:'renwu', slotTypes:['appearance'], subjects:['男生'], stars:2, grain:'句',
    text:'他的头发总是竖着，怎么按都按不平，跑起来一颠一颠，像一把没收好的小扫帚。',
    chunks:['他的头发总是竖着，','怎么按都按不平，','跑起来一颠一颠，','像一把','没收好的小扫帚。'] },
  { id:'p08', genre:'renwu', slotTypes:['appearance'], subjects:['女生'], stars:2, grain:'句',
    text:'她的两条辫子一晃一晃，说话的时候，辫子比人还着急，头跟着一点一点。',
    chunks:['她的两条辫子','一晃一晃，','说话的时候，','辫子比人还着急，','头跟着','一点一点。'] },
  { id:'p09', genre:'renwu', slotTypes:['appearance'], subjects:['老师'], stars:3, grain:'句',
    text:'老师的眼角有几道细细的纹，一笑起来，那些纹就全弯了，像折过的纸又展开。',
    chunks:['老师的眼角','有几道细细的纹，','一笑起来，','那些纹就全弯了，','像折过的纸','又展开。'] },
  { id:'p10', genre:'renwu', slotTypes:['appearance'], subjects:['妈妈'], stars:3, grain:'句',
    text:'妈妈的手背有点粗，指节上还有倒刺，摸我脸的时候，像一片旧棉布。',
    chunks:['妈妈的手背','有点粗，','指节上还有倒刺，','摸我脸的时候，','像一片旧棉布。'] },

  { id:'p11', genre:'renwu', slotTypes:['personality'], subjects:['男生'], stars:3, grain:'句',
    text:'别人还在数题目有几个条件，他的笔已经沙沙地写到第二行，橡皮都来不及用。',
    chunks:['别人还在','数题目有几个条件，','他的笔','已经沙沙地','写到第二行，','橡皮','都来不及用。'] },
  { id:'p12', genre:'renwu', slotTypes:['personality'], subjects:['男生'], stars:3, grain:'片段',
    text:'我忘带尺子那天，他二话没说，把自己那把掰成两半，一半推到我桌上，还说短的更好用。',
    chunks:['我忘带尺子那天，','他二话没说，','把自己那把','掰成两半，','一半','推到我桌上，','还说','短的','更好用。'] },
  { id:'p13', genre:'renwu', slotTypes:['personality'], subjects:['老师'], stars:3, grain:'句',
    text:'老师从不说「你怎么这么笨」，她只把本子翻回第一页，说「再来一次，这次慢一点」。',
    chunks:['老师从不说','「你怎么这么笨」，','她只把本子','翻回第一页，','说','「再来一次，','这次慢一点」。'] },
  { id:'p14', genre:'renwu', slotTypes:['personality'], subjects:['妈妈'], stars:3, grain:'句',
    text:'妈妈嘴上骂我「衣服又乱扔」，手上却已经把它叠好，连袖子都捋平了。',
    chunks:['妈妈嘴上骂我','「衣服又乱扔」，','手上却已经','把它叠好，','连袖子','都捋平了。'] },
  { id:'p15', genre:'renwu', slotTypes:['personality'], subjects:['女生'], stars:2, grain:'句',
    text:'她自己的作业写得慢，却总要先把题目给同学讲明白，讲不完就不出去玩。',
    chunks:['她自己的作业写得慢，','却总要','先把题目','给同学讲明白，','讲不完','就不出去玩。'] },

  { id:'p16', genre:'renwu', slotTypes:['action'], subjects:['男生'], stars:3, grain:'句',
    text:'他把笔一转，身子往后一靠，眼睛盯着题目一动不动，像在跟它较劲，谁叫他都不理。',
    chunks:['他把笔一转，','身子往后一靠，','眼睛盯着题目','一动不动，','像在跟它较劲，','谁叫他','都不理。'] },
  { id:'p17', genre:'renwu', slotTypes:['action'], subjects:['男生'], stars:2, grain:'句',
    text:'上课铃一响，他一个箭步冲进门，书包还在背上晃，鞋跟差点甩掉一只。',
    chunks:['上课铃一响，','他一个箭步冲进门，','书包还在背上晃，','鞋跟','差点甩掉一只。'] },
  { id:'p18', genre:'renwu', slotTypes:['action'], subjects:['老师'], stars:3, grain:'片段',
    text:'老师弯下腰，把我的本子转过来，用红笔在错的地方轻轻点了三下，没说话，只抬头看了我一眼。',
    chunks:['老师弯下腰，','把我的本子','转过来，','用红笔','在错的地方','轻轻点了三下，','没说话，','只抬头','看了我一眼。'] },
  { id:'p19', genre:'renwu', slotTypes:['action'], subjects:['妈妈'], stars:3, grain:'片段',
    text:'妈妈进门先摸一下暖气片，再摸我的手，最后才想起来脱自己的外套，围巾都没解。',
    chunks:['妈妈进门','先摸一下暖气片，','再摸我的手，','最后','才想起来','脱自己的外套，','围巾都没解。'] },
  { id:'p20', genre:'renwu', slotTypes:['action'], subjects:['男生'], stars:2, grain:'句',
    text:'他挠了挠头，把话咽回去，过了好一会儿，才小声说了一句「对不起」。',
    chunks:['他挠了挠头，','把话咽回去，','过了好一会儿，','才小声说了一句','「对不起」。'] },

  { id:'p21', genre:'renwu', slotTypes:['ending'], subjects:['男生'], stars:2, grain:'句',
    text:'我想，班里少了谁都还能上课，少了他的笑声，教室一下子就安静得不对劲。',
    chunks:['我想，','班里少了谁都还能上课，','少了他的笑声，','教室','一下子就安静得不对劲。'] },
  { id:'p22', genre:'renwu', slotTypes:['ending'], subjects:['通用'], stars:1, grain:'句',
    text:'有这样的人在身边，日子好像都变得好过一点，连坏消息听起来都没那么吓人。',
    chunks:['有这样的人在身边，','日子好像','都变得好过一点，','连坏消息','听起来','都没那么吓人。'] },
  { id:'p23', genre:'renwu', slotTypes:['ending'], subjects:['老师'], stars:3, grain:'句',
    text:'长大以后我也许会忘记很多老师和课文名字，但那三下红笔，我大概一辈子都忘不了。',
    chunks:['长大以后','我也许会忘记','很多老师和课文名字，','但那三下红笔，','我大概','一辈子都忘不了。'] },
  { id:'p24', genre:'renwu', slotTypes:['ending'], subjects:['妈妈'], stars:3, grain:'句',
    text:'我以后要早点回家，趁她还没进门，先把暖气片摸一遍，把她要问的话都准备好。',
    chunks:['我以后要早点回家，','趁她还没进门，','先把暖气片摸一遍，','把她要问的话','都准备好。'] },
  { id:'p25', genre:'renwu', slotTypes:['ending'], subjects:['通用'], stars:2, grain:'句',
    text:'有些人不用你夸，也从来不讲大道理，你只要安静地看着他，就学到了东西。',
    chunks:['有些人不用你夸，','也从来不讲大道理，','你只要','安静地看着他，','就学到了东西。'] },

  /* ===================== 写景 ===================== */
  { id:'s01', genre:'xiejing', slotTypes:['opening'], subjects:['通用'], stars:2, grain:'句',
    text:'我一直觉得，一个地方最好看的样子，是不肯随便给人看的，要等某个时候才肯露出来。',
    chunks:['我一直觉得，','一个地方','最好看的样子，','是不肯','随便给人看的，','要等某个时候','才肯露出来。'] },
  { id:'s02', genre:'xiejing', slotTypes:['opening'], subjects:['秋','校园'], stars:2, grain:'句',
    text:'十月一到，校园就悄悄换了一身衣服，走在里面的人，脚步都慢了半拍。',
    chunks:['十月一到，','校园就悄悄','换了一身衣服，','走在里面的人，','脚步都慢了半拍。'] },
  { id:'s03', genre:'xiejing', slotTypes:['opening'], subjects:['雨','公园'], stars:3, grain:'句',
    text:'雨停了，公园像刚洗过脸，草叶上还挂着水珠，连空气闻起来都是干净的。',
    chunks:['雨停了，','公园像刚洗过脸，','草叶上还挂着水珠，','连空气','闻起来都是干净的。'] },
  { id:'s04', genre:'xiejing', slotTypes:['opening'], subjects:['水','家乡'], stars:3, grain:'句',
    text:'村口那条小河，水面不宽，水也不深，却装下了我小时候的整个夏天。',
    chunks:['村口那条小河，','水面不宽，','水也不深，','却装下了','我小时候的整个夏天。'] },
  { id:'s05', genre:'xiejing', slotTypes:['opening'], subjects:['秋'], stars:3, grain:'句',
    text:'秋天不是一天来的，它是一片叶子一片叶子，慢慢从树上挪过来的。',
    chunks:['秋天不是一天来的，','它是一片叶子','一片叶子，','慢慢从树上','挪过来的。'] },

  { id:'s06', genre:'xiejing', slotTypes:['panorama'], subjects:['秋','校园'], stars:3, grain:'句',
    text:'操场边的梧桐排成两行，叶子从这头黄到那头，风一过就往下掉，像铺了一条金毯子。',
    chunks:['操场边的梧桐','排成两行，','叶子从这头黄到那头，','风一过就往下掉，','像铺了','一条金毯子。'] },
  { id:'s07', genre:'xiejing', slotTypes:['panorama'], subjects:['校园'], stars:2, grain:'句',
    text:'远远望去，整个校园安安静静，只有那面旗子在风里一动一动，像在打招呼。',
    chunks:['远远望去，','整个校园安安静静，','只有那面旗子','在风里一动一动，','像在打招呼。'] },
  { id:'s08', genre:'xiejing', slotTypes:['panorama'], subjects:['雨','公园'], stars:2, grain:'句',
    text:'雨后的公园到处发亮，草地、长椅、石板路，全都被雨洗过一遍，湿得发光。',
    chunks:['雨后的公园到处发亮，','草地、长椅、石板路，','全都被雨','洗过一遍，','湿得发光。'] },
  { id:'s09', genre:'xiejing', slotTypes:['panorama'], subjects:['水','家乡'], stars:3, grain:'句',
    text:'小河从村东一直弯到村西，太阳一照，就像谁随手扔下的一条银带子。',
    chunks:['小河从村东','一直弯到村西，','太阳一照，','就像谁随手扔下的','一条银带子。'] },
  { id:'s10', genre:'xiejing', slotTypes:['panorama'], subjects:['通用'], stars:1, grain:'句',
    text:'天灰蒙蒙的，风把云压得很低，远处的树只剩下一道模糊的影子。',
    chunks:['天灰蒙蒙的，','风把云压得很低，','远处的树','只剩下','一道模糊的影子。'] },

  { id:'s11', genre:'xiejing', slotTypes:['closeup'], subjects:['秋','校园'], stars:3, grain:'句',
    text:'一片梧桐叶打着旋落在我脚边，叶脉清清楚楚，像一只摊开的小手掌。',
    chunks:['一片梧桐叶','打着旋','落在我脚边，','叶脉清清楚楚，','像一只','摊开的小手掌。'] },
  { id:'s12', genre:'xiejing', slotTypes:['closeup'], subjects:['通用'], stars:2, grain:'句',
    text:'树干上有一道旧疤，凸出一圈，摸上去凉凉的、硬硬的，像结痂的伤口。',
    chunks:['树干上','有一道旧疤，','凸出一圈，','摸上去','凉凉的、硬硬的，','像结痂的伤口。'] },
  { id:'s13', genre:'xiejing', slotTypes:['closeup'], subjects:['雨','公园'], stars:3, grain:'句',
    text:'一颗水珠停在叶尖上，晃了晃，越坠越大，最后「嗒」的一声掉进草里。',
    chunks:['一颗水珠','停在叶尖上，','晃了晃，','越坠越大，','最后「嗒」的一声','掉进草里。'] },
  { id:'s14', genre:'xiejing', slotTypes:['closeup'], subjects:['水','家乡'], stars:3, grain:'句',
    text:'河底的石头被水磨得光滑，一块挨着一块，水一冲过去，连纹路都看得清清楚楚。',
    chunks:['河底的石头','被水磨得光滑，','一块挨着一块，','水一冲过去，','连纹路','都看得清清楚楚。'] },
  { id:'s15', genre:'xiejing', slotTypes:['closeup'], subjects:['雨','公园'], stars:2, grain:'句',
    text:'花瓣上还挂着雨珠，风一抖就滚下来，那点红被水一浸，红得像要滴下来。',
    chunks:['花瓣上还挂着雨珠，','风一抖就滚下来，','那点红','被水一浸，','红得像要滴下来。'] },

  { id:'s16', genre:'xiejing', slotTypes:['dynamic'], subjects:['秋','校园'], stars:3, grain:'句',
    text:'风一吹，落叶就沙沙地跑起来，追着人的脚后跟，怎么躲都躲不开。',
    chunks:['风一吹，','落叶就沙沙地','跑起来，','追着人的脚后跟，','怎么躲','都躲不开。'] },
  { id:'s17', genre:'xiejing', slotTypes:['dynamic'], subjects:['校园'], stars:2, grain:'句',
    text:'远处传来一阵哨子声，哨音一落，操场上就响起一片跑步的脚步声。',
    chunks:['远处','传来一阵哨子声，','哨音一落，','操场上','就响起','一片跑步的脚步声。'] },
  { id:'s18', genre:'xiejing', slotTypes:['dynamic'], subjects:['雨','公园'], stars:3, grain:'句',
    text:'树上的水珠被风摇下来，噼里啪啦砸在地上，像头顶又下了一场小雨。',
    chunks:['树上的水珠','被风摇下来，','噼里啪啦','砸在地上，','像头顶','又下了一场小雨。'] },
  { id:'s19', genre:'xiejing', slotTypes:['dynamic'], subjects:['水','家乡'], stars:3, grain:'片段',
    text:'河水哗啦啦地淌，几只鸭子摇摇摆摆走下去，把安静的水面搅得一圈一圈。',
    chunks:['河水哗啦啦地淌，','几只鸭子','摇摇摆摆走下去，','把安静的水面','搅得一圈一圈。'] },
  { id:'s20', genre:'xiejing', slotTypes:['dynamic'], subjects:['通用'], stars:2, grain:'句',
    text:'蝉不知躲在树叶的哪一层里，一声接一声地叫，越叫太阳越毒，越叫越热。',
    chunks:['蝉','不知躲在','树叶的哪一层里，','一声接一声地叫，','越叫太阳越毒，','越叫越热。'] },

  { id:'s21', genre:'xiejing', slotTypes:['ending'], subjects:['校园','秋'], stars:2, grain:'句',
    text:'我在那排树下站了很久，直到上课铃响，才把我从秋天里叫回去。',
    chunks:['我在那排树下','站了很久，','直到上课铃响，','才把我','从秋天里','叫回去。'] },
  { id:'s22', genre:'xiejing', slotTypes:['ending'], subjects:['通用'], stars:3, grain:'句',
    text:'我忽然明白，好看的地方不用走远，也不用在照片里找，它就在我天天路过、从来没认真看过的那条路上。',
    chunks:['我忽然明白，','好看的地方','不用走远，','也不用在照片里找，','它就在我天天路过、','从来没认真看过的','那条路上。'] },
  { id:'s23', genre:'xiejing', slotTypes:['ending'], subjects:['雨','公园'], stars:3, grain:'句',
    text:'那天的凉气我到现在还记得，一想起来，心里就像被擦过一遍，干干净净的。',
    chunks:['那天的凉气','我到现在还记得，','一想起来，','心里就像被擦过一遍，','干干净净的。'] },
  { id:'s24', genre:'xiejing', slotTypes:['ending'], subjects:['水','家乡'], stars:3, grain:'句',
    text:'不管我以后走多远，那条小河哗啦啦的声音，都会在我耳朵里一直流着。',
    chunks:['不管我以后走多远，','那条小河','哗啦啦的声音，','都会在我耳朵里','一直流着。'] },
  { id:'s25', genre:'xiejing', slotTypes:['ending'], subjects:['秋'], stars:2, grain:'句',
    text:'我把这片叶子夹进语文书里，下次翻到那一页，就能再看见这个秋天。',
    chunks:['我把这片叶子','夹进语文书里，','下次翻到那一页，','就能再看见','这个秋天。'] },

  /* ===================== 叙事 ===================== */
  { id:'e01', genre:'xushi', slotTypes:['opening'], subjects:['通用'], stars:1, grain:'句',
    text:'有一件事，过了这么久，我还是记得清清楚楚，连当时的天气都没忘。',
    chunks:['有一件事，','过了这么久，','我还是','记得清清楚楚，','连当时的天气','都没忘。'] },
  { id:'e02', genre:'xushi', slotTypes:['opening'], subjects:['运动会','比赛'], stars:2, grain:'句',
    text:'那天的太阳很好，风也大，操场上的旗子被吹得啪啪响，怎么也停不下来。',
    chunks:['那天的太阳很好，','风也大，','操场上的旗子','被吹得啪啪响，','怎么也停不下来。'] },
  { id:'e03', genre:'xushi', slotTypes:['opening'], subjects:['犯错','反思'], stars:3, grain:'句',
    text:'有些错，做的时候只用了一秒，认的时候却要花一整天，攒够勇气才敢开口。',
    chunks:['有些错，','做的时候','只用了一秒，','认的时候','却要花一整天，','攒够勇气','才敢开口。'] },
  { id:'e04', genre:'xushi', slotTypes:['opening'], subjects:['第一次','家务'], stars:2, grain:'句',
    text:'我一直以为炒个蛋是件很简单的事，两分钟就能端上桌，直到我自己站到灶台前。',
    chunks:['我一直以为','炒个蛋','是件很简单的事，','两分钟就能端上桌，','直到我自己','站到灶台前。'] },
  { id:'e05', genre:'xushi', slotTypes:['opening'], subjects:['通用'], stars:2, grain:'句',
    text:'事情说起来不大，讲给别人听也就一两句，可它把我心里的某个地方，悄悄挪动了一下。',
    chunks:['事情说起来不大，','讲给别人听','也就一两句，','可它','把我心里的某个地方，','悄悄挪动了一下。'] },

  { id:'e06', genre:'xushi', slotTypes:['process'], subjects:['运动会','比赛'], stars:2, grain:'片段',
    text:'第一棒冲出去的时候，全班都在喊。声音一浪一浪地推过来，我攥紧了手心。',
    chunks:['第一棒','冲出去的时候，','全班都在喊。','声音','一浪一浪地推过来，','我攥紧了手心。'] },
  { id:'e07', genre:'xushi', slotTypes:['process'], subjects:['犯错','反思'], stars:3, grain:'片段',
    text:'水杯是在我一转身的时候倒下去的。它先是晃了两下，然后就在地上碎成了好几块。',
    chunks:['水杯','是在我一转身的时候','倒下去的。','它先是晃了两下，','然后','就在地上','碎成了好几块。'] },
  { id:'e08', genre:'xushi', slotTypes:['process'], subjects:['第一次','家务'], stars:2, grain:'片段',
    text:'我照着妈妈说的，先倒油，再打蛋。蛋壳一磕，蛋液顺着碗边滑下去，有一小块壳也跟着掉进去了。',
    chunks:['我照着妈妈说的，','先倒油，','再打蛋。','蛋壳一磕，','蛋液','顺着碗边滑下去，','有一小块壳','也跟着掉进去了。'] },
  { id:'e09', genre:'xushi', slotTypes:['process'], subjects:['通用'], stars:1, grain:'句',
    text:'事情就这样一步一步往前走，中间谁也没喊停，等我反应过来，已经收不了场了。',
    chunks:['事情就这样','一步一步往前走，','中间谁也没喊停，','等我反应过来，','已经收不了场了。'] },
  { id:'e10', genre:'xushi', slotTypes:['process'], subjects:['运动会','比赛'], stars:3, grain:'片段',
    text:'轮到我了。我伸出右手往后探，眼睛却死死盯着前面的白线，只听见身后的脚步声越来越近。',
    chunks:['轮到我了。','我伸出右手','往后探，','眼睛却死死盯着','前面的白线，','只听见身后的','脚步声','越来越近。'] },

  { id:'e11', genre:'xushi', slotTypes:['inner'], subjects:['运动会','比赛'], stars:3, grain:'句',
    text:'接力棒交到我手里之后，我心里只剩一句话在转：别掉，千万别掉。',
    chunks:['接力棒交到我手里之后，','我心里','只剩一句话在转：','别掉，','千万别掉。'] },
  { id:'e12', genre:'xushi', slotTypes:['inner'], subjects:['犯错','反思'], stars:3, grain:'片段',
    text:'那一下午我都坐得笔直，谁一走过我旁边，我的心就往下沉一点。我一边盼着没人发现，一边又受不了自己这么盼着。',
    chunks:['那一下午','我都坐得笔直，','谁一走过我旁边，','我的心','就往下沉一点。','我一边盼着没人发现，','一边','又受不了自己','这么盼着。'] },
  { id:'e13', genre:'xushi', slotTypes:['inner'], subjects:['第一次','家务'], stars:2, grain:'句',
    text:'油在锅里一响，我手一抖，铲子都拿不稳，脑子里只剩一句话：完了完了。',
    chunks:['油在锅里一响，','我手一抖，','铲子都拿不稳，','脑子里','只剩一句话：','完了完了。'] },
  { id:'e14', genre:'xushi', slotTypes:['inner'], subjects:['通用'], stars:2, grain:'句',
    text:'我的心跳得厉害，咚咚咚的，好像有谁在里面敲鼓，捂住耳朵都听得见。',
    chunks:['我的心跳得厉害，','咚咚咚的，','好像有谁在里面敲鼓，','捂住耳朵','都听得见。'] },
  { id:'e15', genre:'xushi', slotTypes:['inner'], subjects:['犯错','反思'], stars:3, grain:'句',
    text:'我发现最难的不是被人骂几句，而是从那以后，我自己都不敢看自己。',
    chunks:['我发现','最难的不是被人骂几句，','而是从那以后，','我自己','都不敢看自己。'] },

  { id:'e16', genre:'xushi', slotTypes:['climax'], subjects:['运动会','比赛'], stars:3, grain:'片段',
    text:'棒子拍进我手心的那一下，滑了半寸。我猛地一收指头，把它攥死，然后头也不回地冲了出去。',
    chunks:['棒子','拍进我手心的那一下，','滑了半寸。','我猛地一收指头，','把它攥死，','然后','头也不回地','冲了出去。'] },
  { id:'e17', genre:'xushi', slotTypes:['climax'], subjects:['犯错','反思'], stars:3, grain:'片段',
    text:'我站到他面前，喉咙像被堵住了。我听见自己的声音很小：「那个杯子……是我打碎的。」说完，肩膀忽然就松了。',
    chunks:['我站到','他面前，','喉咙','像被堵住了。','我听见','自己的','声音很小：','「那个杯子……','是我打碎的。」','说完，','肩膀','忽然','就松了。'] },
  { id:'e18', genre:'xushi', slotTypes:['climax'], subjects:['第一次','家务'], stars:3, grain:'片段',
    text:'油花「噌」地跳起来，溅到我手背上。我叫了一声，铲子差点扔出去，可还是咬着牙把蛋翻了个面。',
    chunks:['油花「噌」地跳起来，','溅到我手背上。','我叫了一声，','铲子','差点扔出去，','可还是咬着牙','把蛋翻了个面。'] },
  { id:'e19', genre:'xushi', slotTypes:['climax'], subjects:['通用'], stars:2, grain:'句',
    text:'就在那一秒，操场上的喊声、风声，好像全都消失了，只剩下我自己的心跳。',
    chunks:['就在那一秒，','操场上的喊声、风声，','好像','全都消失了，','只剩下','我自己的心跳。'] },
  { id:'e20', genre:'xushi', slotTypes:['climax'], subjects:['比赛','运动会'], stars:2, grain:'句',
    text:'我冲过终点线，腿一软就蹲下了，这时候才发现，自己从弯道开始就一直忘了呼吸。',
    chunks:['我冲过终点线，','腿一软就蹲下了，','这时候才发现，','自己从弯道开始','就一直忘了呼吸。'] },

  { id:'e21', genre:'xushi', slotTypes:['ending'], subjects:['运动会','比赛'], stars:2, grain:'句',
    text:'我们最后没拿第一，可那根棒子，我从接过来那一刻攥到最后，一路都没掉。',
    chunks:['我们最后没拿第一，','可那根棒子，','我从接过来那一刻','攥到最后，','一路都没掉。'] },
  { id:'e22', genre:'xushi', slotTypes:['ending'], subjects:['犯错','反思'], stars:3, grain:'句',
    text:'从那以后我知道了，认错这件事要趁早，拖得越久，它在心里就压得越重。',
    chunks:['从那以后','我知道了，','认错这件事','要趁早，','拖得越久，','它在心里','就压得越重。'] },
  { id:'e23', genre:'xushi', slotTypes:['ending'], subjects:['第一次','家务'], stars:3, grain:'句',
    text:'那盘蛋边上有点焦，样子也不好看，可它是我第一次自己端上桌的菜。',
    chunks:['那盘蛋','边上有点焦，','样子也不好看，','可它是我','第一次自己','端上桌的菜。'] },
  { id:'e24', genre:'xushi', slotTypes:['ending'], subjects:['通用'], stars:1, grain:'句',
    text:'这件事我记到了现在，写下来又读了一遍，大概以后还会记很久很久。',
    chunks:['这件事我记到了现在，','写下来','又读了一遍，','大概以后','还会记很久很久。'] },
  { id:'e25', genre:'xushi', slotTypes:['ending'], subjects:['第一次','家务','通用'], stars:3, grain:'句',
    text:'原来很多事不是我不会，也不是有多难，只是我还没挽起袖子，自己从头做过一次。',
    chunks:['原来很多事','不是我不会，','也不是有多难，','只是我还没','挽起袖子，','自己从头','做过一次。'] },

  /* ===================== 状物 ===================== */
  { id:'t01', genre:'zhuangwu', slotTypes:['opening'], subjects:['通用'], stars:1, grain:'句',
    text:'我有一样东西，别人看了都说普通，我却在里面存了一堆事，一直舍不得换。',
    chunks:['我有一样东西，','别人看了都说普通，','我却在里面','存了一堆事，','一直舍不得换。'] },
  { id:'t02', genre:'zhuangwu', slotTypes:['opening'], subjects:['文具','物品'], stars:2, grain:'句',
    text:'我的书包里住着一个老伙计，从三年级开学第一天起，跟了我整整两年。',
    chunks:['我的书包里','住着一个老伙计，','从三年级开学','第一天起，','跟了我整整两年。'] },
  { id:'t03', genre:'zhuangwu', slotTypes:['opening'], subjects:['植物'], stars:2, grain:'句',
    text:'窗台上那盆绿萝，不吵不闹也不开花，是家里最不声不响的一个成员。',
    chunks:['窗台上那盆绿萝，','不吵不闹','也不开花，','是家里','最不声不响的','一个成员。'] },
  { id:'t04', genre:'zhuangwu', slotTypes:['opening'], subjects:['动物'], stars:3, grain:'句',
    text:'我家有一位成员，从来不说话，可它总是比谁都先知道我快到家了。',
    chunks:['我家有一位成员，','从来不说话，','可它总是','比谁都先知道','我快到家了。'] },
  { id:'t05', genre:'zhuangwu', slotTypes:['opening'], subjects:['通用'], stars:2, grain:'句',
    text:'东西用久了会变样，掉漆、磨白、边角发圆，用着用着，也就变亲了。',
    chunks:['东西','用久了会变样，','掉漆、磨白、边角发圆，','用着用着，','也就变亲了。'] },

  { id:'t06', genre:'zhuangwu', slotTypes:['shape'], subjects:['文具','物品'], stars:2, grain:'句',
    text:'它是蓝色的，长方形，比我的手掌大一点，四个角全磨圆了，蓝漆也淡了。',
    chunks:['它是蓝色的，','长方形，','比我的手掌大一点，','四个角全磨圆了，','蓝漆也淡了。'] },
  { id:'t07', genre:'zhuangwu', slotTypes:['shape'], subjects:['植物'], stars:3, grain:'句',
    text:'叶子一片压着一片垂下来，绿得发亮，风一动就轻轻晃，像一串小小的心。',
    chunks:['叶子','一片压着一片垂下来，','绿得发亮，','风一动就轻轻晃，','像一串小小的心。'] },
  { id:'t08', genre:'zhuangwu', slotTypes:['shape'], subjects:['动物'], stars:3, grain:'句',
    text:'它一身黄毛，只有肚子那块是白的，尾巴短短一截，不管高兴还是挨骂，都翘着。',
    chunks:['它一身黄毛，','只有肚子那块是白的，','尾巴短短一截，','不管高兴还是挨骂，','都翘着。'] },
  { id:'t09', genre:'zhuangwu', slotTypes:['shape'], subjects:['通用'], stars:1, grain:'句',
    text:'它不大也不小，往我的抽屉里一放，正好占满一层，像专门给我做的。',
    chunks:['它不大','也不小，','往我的抽屉里一放，','正好占满一层，','像专门给我做的。'] },
  { id:'t10', genre:'zhuangwu', slotTypes:['shape'], subjects:['文具','物品'], stars:2, grain:'句',
    text:'盖子上原来印着一只小熊，被我摸了两年，现在只剩下两只耳朵，还看得出来。',
    chunks:['盖子上','原来印着一只小熊，','被我摸了两年，','现在只剩下','两只耳朵，','还看得出来。'] },

  { id:'t11', genre:'zhuangwu', slotTypes:['feature'], subjects:['文具','物品'], stars:3, grain:'句',
    text:'左边那个角磕掉了一小块漆，露出银色的铁皮，摸上去有点扎手，也提醒我它陪我摔过跤。',
    chunks:['左边那个角','磕掉了一小块漆，','露出银色的铁皮，','摸上去有点扎手，','也提醒我','它陪我摔过跤。'] },
  { id:'t12', genre:'zhuangwu', slotTypes:['feature'], subjects:['植物'], stars:3, grain:'句',
    text:'凑近仔细看，每片叶子的背面，都藏着几道浅浅的筋，像一张谁也没发现的小地图。',
    chunks:['凑近仔细看，','每片叶子的背面，','都藏着','几道浅浅的筋，','像一张','谁也没发现的小地图。'] },
  { id:'t13', genre:'zhuangwu', slotTypes:['feature'], subjects:['动物'], stars:3, grain:'句',
    text:'它右耳朵尖上有一小撮白毛，像被人点了一下，我一眼就能从一群狗里把它认出来。',
    chunks:['它右耳朵尖上','有一小撮白毛，','像被人点了一下，','我一眼就能','从一群狗里','把它认出来。'] },
  { id:'t14', genre:'zhuangwu', slotTypes:['feature'], subjects:['通用'], stars:2, grain:'句',
    text:'用得最多的那一处，颜色已经比别的地方浅了一截，一看就知道我平时最常摸哪儿。',
    chunks:['用得最多的那一处，','颜色已经','比别的地方浅了一截，','一看就知道','我平时','最常摸哪儿。'] },
  { id:'t15', genre:'zhuangwu', slotTypes:['feature'], subjects:['文具','物品'], stars:2, grain:'句',
    text:'一打开盖子，里面挤得满满的，铅笔、尺子、橡皮一层压一层，像在争着往外跳。',
    chunks:['一打开盖子，','里面挤得满满的，','铅笔、尺子、橡皮','一层压一层，','像在争着往外跳。'] },

  { id:'t16', genre:'zhuangwu', slotTypes:['usage'], subjects:['文具','物品'], stars:3, grain:'片段',
    text:'考试前我总要把它整理一遍，笔尖朝一个方向排好。做完这件事，我心里才算踏实。',
    chunks:['考试前','我总要把它整理一遍，','笔尖','朝一个方向排好。','做完这件事，','我心里才算踏实。'] },
  { id:'t17', genre:'zhuangwu', slotTypes:['usage'], subjects:['植物'], stars:3, grain:'片段',
    text:'我出去玩了一个星期，回来发现它又长出两片新叶，正好搭到了窗框上，像在等我。',
    chunks:['我出去玩了一个星期，','回来发现','它又长出两片新叶，','正好','搭到了窗框上，','像在等我。'] },
  { id:'t18', genre:'zhuangwu', slotTypes:['usage'], subjects:['动物'], stars:3, grain:'片段',
    text:'每天放学，我还没走到楼下，它就已经在门口坐着了。门一开，它先绕着我转三圈，才肯让我进屋。',
    chunks:['每天放学，','我还没走到楼下，','它就已经','在门口坐着了。','门一开，','它先绕着我转三圈，','才肯让我进屋。'] },
  { id:'t19', genre:'zhuangwu', slotTypes:['usage'], subjects:['通用'], stars:1, grain:'句',
    text:'我每天都要用到它，一天也离不开，忘在家里那次我一整天都不自在。',
    chunks:['我每天','都要用到它，','一天也离不开，','忘在家里那次','我一整天','都不自在。'] },
  { id:'t20', genre:'zhuangwu', slotTypes:['usage'], subjects:['文具','物品'], stars:2, grain:'句',
    text:'同桌的笔没水了、橡皮找不着了，第一个想到的，都是来翻我这个盒子。',
    chunks:['同桌的笔没水了、','橡皮找不着了，','第一个想到的，','都是来翻','我这个盒子。'] },

  { id:'t21', genre:'zhuangwu', slotTypes:['ending'], subjects:['文具','物品'], stars:2, grain:'句',
    text:'新的当然更好看，店里的哪个都比它新，可我还是想先把这一个用完。',
    chunks:['新的当然更好看，','店里的哪个都比它新，','可我还是','想先把这一个','用完。'] },
  { id:'t22', genre:'zhuangwu', slotTypes:['ending'], subjects:['植物'], stars:3, grain:'句',
    text:'它不用人夸，也没人催，照样一天一天往上长，长得理直气壮，我有点羡慕它。',
    chunks:['它不用人夸，','也没人催，','照样一天一天往上长，','长得理直气壮，','我有点羡慕它。'] },
  { id:'t23', genre:'zhuangwu', slotTypes:['ending'], subjects:['动物'], stars:3, grain:'句',
    text:'它不会说一句话，可我知道，只要它趴在那儿，家里的门才算真正的门。',
    chunks:['它不会说一句话，','可我知道，','只要它趴在那儿，','家里的门','才算真正的门。'] },
  { id:'t24', genre:'zhuangwu', slotTypes:['ending'], subjects:['通用'], stars:2, grain:'句',
    text:'一样东西陪你久了，装过你的秘密，听过你嘟囔的话，就不只是一件东西了。',
    chunks:['一样东西陪你久了，','装过你的秘密，','听过你嘟囔的话，','就不只是','一件东西了。'] },
  { id:'t25', genre:'zhuangwu', slotTypes:['ending'], subjects:['通用'], stars:1, grain:'句',
    text:'不管以后再添多少新东西，这一件，我都会一直好好地留着，谁也不给。',
    chunks:['不管以后','再添多少新东西，','这一件，','我都会','一直好好地留着，','谁也不给。'] }
];

/* 浏览器里 module 不存在，这行自动跳过；Node（server.js）靠它拿到同一份素材库。 */
if (typeof module !== 'undefined') module.exports = { CORPUS };
